version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=linglong
      - MYSQL_ROOT_PASSWORD=linglong8s
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
    ]
  server:
    container_name: 'linglong-server'
    build: .
    ports:
      - "18000:18000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
  web:
    container_name: 'linglong-web'
    restart: always
    build: ./web
    ports:
      - 8001:8001
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
